version: "3"
services:
  postgres:
    image: postgres:latest
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
  master:
    build: .
    command: /srv/master.py start
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "80:5000"
    volumes:
      - ".:/srv"
  node:
    build: .
    command: /srv/node.py start
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5000:5000"
    volumes:
      - ".:/srv"
