---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: fpm
  template:
    metadata:
      labels:
        app: fpm
    spec:
      containers:
        - name: fpm
          image: nextcloud:stable-fpm
          envFrom:
            - secretRef:
                name: nextcloud-env
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: core
              mountPath: /var/www/html
            - name: apps
              mountPath: /var/www/html/custom_apps
            - name: conf
              mountPath: /var/www/html/config
            - name: data
              mountPath: /var/lib/nextcloud
      volumes:
        - name: core
          persistentVolumeClaim:
            claimName: core
        - name: apps
          persistentVolumeClaim:
            claimName: apps
        - name: conf
          persistentVolumeClaim:
            claimName: conf
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: fpm
  namespace: nextcloud
spec:
  selector:
    app: fpm
  ports:
    - name: fpm
      port: 9000
      protocol: TCP
      targetPort: 9000
