---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nextcloud
data: 
  nginx.conf: |
    user www-data www-data;
    worker_processes auto;

    error_log off;

    events {
      worker_connections 512;
    }

    http {
      include mime.types;
      default_type application/octet-stream;

      server {
        listen      80;
        server_name _;

        location / {
          root  /usr/share/nginx/html;
          index index.htm index.html;
        }
      }

      upstream nextcloud-fpm {
        server fpm:9000;
      }

      server {
        listen      80;
        server_name cloud.internal;

        client_max_body_size 512M;
        fastcgi_buffers 64 4K;

        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

        #add_header Referrer-Policy                      "no-referrer"   always;
        #add_header X-Content-Type-Options               "nosniff"       always;
        #add_header X-Download-Options                   "noopen"        always;
        #add_header X-Frame-Options                      "SAMEORIGIN"    always;
        #add_header X-Permitted-Cross-Domain-Policies    "none"          always;
        #add_header X-Robots-Tag                         "none"          always;
        #add_header X-XSS-Protection                     "1; mode=block" always;

        fastcgi_hide_header X-Powered-By;
        root                /var/www/html;

        index index.php index.html /index.php$request_uri;

        location = / {
            if ( $http_user_agent ~ ^DavClnt ) {
                return 302 /remote.php/webdav/$is_args$args;
            }
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location ^~ /.well-known {
            rewrite ^/\.well-known/host-meta\.json  /public.php?service=host-meta-json  last;
            rewrite ^/\.well-known/host-meta        /public.php?service=host-meta       last;
            rewrite ^/\.well-known/webfinger        /public.php?service=webfinger       last;
            rewrite ^/\.well-known/nodeinfo         /public.php?service=nodeinfo        last;

            location = /.well-known/carddav     { return 301 /remote.php/dav/; }
            location = /.well-known/caldav      { return 301 /remote.php/dav/; }

            try_files $uri $uri/ =404;
        }

        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/)  { return 404; }
        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)              { return 404; }

        location ~ \.php(?:$|/) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            set $path_info $fastcgi_path_info;

            try_files $fastcgi_script_name =404;

            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param HTTPS on;

            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass nextcloud-fpm;

            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
        }

        location ~ \.(?:css|js|svg|gif)$ {
            try_files $uri /index.php$request_uri;
            expires 6M;
            access_log off;
        }

        location ~ \.woff2?$ {
            try_files $uri /index.php$request_uri;
            expires 7d;
            access_log off;
        }

        location / {
            try_files $uri $uri/ /index.php$request_uri;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: core
              mountPath: /var/www/html
            - name: apps
              mountPath: /var/www/html/custom_apps
            - name: data
              mountPath: /var/lib/nextcloud
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: core
          persistentVolumeClaim:
            claimName: core
        - name: apps
          persistentVolumeClaim:
            claimName: apps
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nextcloud
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
